version: '3'

networks:
  profile-app-network:

# volumes:
#   profile-app-data:
#     driver: local

services:
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    expose:
     - "27017"
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin                
     - MONGO_INITDB_ROOT_PASSWORD=password
    networks: 
      - profile-app-network
    # volumes:
    #   - profile-app-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin                
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
    networks: 
      - profile-app-network
  the-profile-app:
    build: ./profile-app
    environment:
     - MONGODB_ADMINUSERNAME=admin                
     - MONGODB_ADMINPASSWORD=password
     - MONGODB_SERVER=mongodb
    networks:
      - profile-app-network
    ports:
     - 3000:3000